### ISSUE TITLE
dotnet telplin tool exception on type alias

### ISSUE THREAD

**Issue by TheAngryByrd** [nojaf/telplin#49]
```
dotnet telplin FsToolkit.ErrorHandling.TaskResult.fsproj

Exception for (495, 5) (495,15) in TaskResultCE.fs
System.Exception: Failed to resolve symbols for (495, 5) (495,15)
   at Telplin.TypedTree.Resolver.findTypeSymbol@57(FSharpSymbolUse[] allSymbols, RangeProxy proxyRange) in C:\Users\nojaf\Projects\telplin\src\Telplin.TypedTree\TypedTree.fs:line 63
   at Telplin.TypedTree.Resolver.mkResolverFor@228.Telplin.Common.TypedTreeInfoResolver.GetTypeTyparNames(RangeProxy range) in C:\Users\nojaf\Projects\telplin\src\Telplin.TypedTree\TypedTree.fs:line 273
Unhandled exception. System.Exception: Failed to resolve symbols for (495, 5) (495,15)
   at Telplin.TypedTree.Resolver.mkResolverFor@228.Telplin.Common.TypedTreeInfoResolver.GetTypeTyparNames(RangeProxy range) in C:\Users\nojaf\Projects\telplin\src\Telplin.TypedTree\TypedTree.fs:line 282
   at Telplin.UntypedTree.Writer.mkTypeDefn(TypedTreeInfoResolver resolver, TypeDefn typeDefn) in C:\Users\nojaf\Projects\telplin\src\Telplin.UntypedTree\UntypedTree.fs:line 320
   at Telplin.UntypedTree.Writer.mkModuleDecl(TypedTreeInfoResolver resolver, ModuleDecl mdl) in C:\Users\nojaf\Projects\telplin\src\Telplin.UntypedTree\UntypedTree.fs:line 548
   at Telplin.UntypedTree.Writer.decls@611.Invoke(ModuleDecl mdl)
   at Microsoft.FSharp.Primitives.Basics.List.chooseToFreshConsTail[a,b](FSharpList`1 cons, FSharpFunc`2 f, FSharpList`1 xs) in D:\a\_work\1\s\src\FSharp.Core\local.fs:line 177
   at Microsoft.FSharp.Primitives.Basics.List.choose[T,TResult](FSharpFunc`2 f, FSharpList`1 xs) in D:\a\_work\1\s\src\FSharp.Core\local.fs:line 192
   at Microsoft.FSharp.Collections.ListModule.Choose[T,TResult](FSharpFunc`2 chooser, FSharpList`1 list) in D:\a\_work\1\s\src\FSharp.Core\list.fs:line 206
   at Telplin.UntypedTree.Writer.mkModuleOrNamespace(TypedTreeInfoResolver resolver, ModuleOrNamespaceNode moduleNode) in C:\Users\nojaf\Projects\telplin\src\Telplin.UntypedTree\UntypedTree.fs:line 611
   at Telplin.UntypedTree.Writer.mkSignatureFile(TypedTreeInfoResolver resolver, String code) in C:\Users\nojaf\Projects\telplin\src\Telplin.UntypedTree\UntypedTree.fs:line 622
   at Program.main$cont@88-1(ParseResults`1 arguments, FSharpChecker checker, FSharpProjectOptions projectOptions, Unit unitVar) in C:\Users\nojaf\Projects\telplin\src\Telplin\Program.fs:line 97
   at Program.main$cont@39(ParseResults`1 arguments, Unit unitVar) in C:\Users\nojaf\Projects\telplin\src\Telplin\Program.fs:line 87
   at Program.main(String[] args) in C:\Users\nojaf\Projects\telplin\src\Telplin\Program.fs:line 36

```

Which points to a [type alias](https://github.com/demystifyfp/FsToolkit.ErrorHandling/blob/master/src/FsToolkit.ErrorHandling.TaskResult/TaskResultCE.fs#L495). Oddly I can't get it to reproduce in the [online tool](https://nojaf.com/telplin/#data=N4KABGBECWC2AOAbAprZA7ALgQ09A9upAFxTrZoDO82AxsmAGKUAq%2B%2BiA1tJgHQCiAJ0H5BACWzoAJomjoA5gB10y-PAxgAygE9KmVLxYALQcmxS58w9kqdKy5QHpnYFjc4AeAErJKAV0RMDwByFgAaMGChEUEAPljlTG11V3cff0CQ8Mjo0ViwAF5U229fAKDQiKjhPNjIEABfIA).

Version: telplin 0.4.0

**Comment by nojaf** [comment]
The gut feeling here is that the condition defines are not taken into account.
`NETSTANDARD2_0` will most likely be set for the typed tree parts and the untyped tree didn't take those into account when parsing. So, it can't resolve any symbols for the typed tree because the untyped tree didn't specify any defines.
It should at the verify least re-use the same defines in the untyped tree parsing, which is something I hope to cover with https://github.com/nojaf/telplin/pull/46
